[env:esp32-c6-mini]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
    -I include
    -D USE_EMULATOR=1

[env:esp32-c6-mini-tcm]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
    -I include
    -D USE_EMULATOR=0
